# Generated by Django 3.2.12 on 2022-02-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_third_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='identity_card',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
