# Generated by Django 3.2.12 on 2022-02-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_identity_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.IntegerField(choices=[(1, 'Software Developer'), (2, 'DevOps Specialists'), (3, 'QA Engineer')], default=1),
            preserve_default=False,
        ),
    ]
