# Generated by Django 3.2.12 on 2022-02-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('first_name',)},
        ),
        migrations.AddField(
            model_name='department',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
